version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run UI Tests with Nightwatch
          command: npm run test:ui

  api-tests:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Start mock server (in background)
          command: |
            npm run dev &
            sleep 3
      - run:
          name: Run API Tests with Jest
          command: npm run test:api

      - store_artifacts:
          path: report.html
          destination: api-test-report.html

workflows:
  version: 2
  test_all:
    jobs:
      - ui-tests
      - api-tests
