version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17-browsers

jobs:
  run-ui-tests:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install UI test dependencies
          command: |
            npm install
      - run:
          name: Run UI tests
          command: |
            npm run test:ui
      - store_artifacts:
          path: UI-test/tests_output
          destination: ui-test-report

  run-api-tests:
    executor: node-executor
    working_directory: ~/project/API-tests/mock-user-auth
    steps:
      - checkout
      - run:
          name: Install API test dependencies
          command: |
            npm install
      - run:
          name: Start API server in background
          command: |
            node API-tests/mock-user-auth/components/mock/routes/index.js &
            sleep 3
      - run:
          name: Run API tests
          command: |
            node API-tests/mock-user-auth/components/mock/routes/index.js &
            npm run test:api
      - store_artifacts:
          path: API-tests/mock-user-auth/components/mock/routes/report.html
          destination: api-test-report

workflows:
  version: 2
  run-tests:
    jobs:
      - run-api-tests
      - run-ui-tests:
          requires:
            - run-api-tests
