version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17-browsers

jobs:
  run-ui-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install
            npm install nightwatch-html-reporter --save-dev

      - run:
          name: Run UI Tests with Nightwatch
          command: npm run test:ui

      - store_artifacts:
          path: UI-test/reports
          destination: ui-test-report

  run-api-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start mock server
          command: |
            npm run dev &
            sleep 5

      - run:
          name: Run API Tests with Jest
          command: npm run test:api

      - store_artifacts:
          path: mock-user-auth/report.html
          destination: api-test-report

workflows:
  version: 2
  run-all-tests:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
