version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17-browsers

jobs:
  run-ui-tests:
    executor: node-executor
    working_directory: ~/project/UI-test
    steps:
      - checkout
      - run:
          name: Install UI test dependencies
          command: |
            cd UI-test
            npm install
      - run:
          name: Run UI tests
          command: |
            npm run test:ui
      - store_artifacts:
          path: UI-test/tests_output
          destination: ui-test-report

  run-api-tests:
    executor: node-executor
    working_directory: ~/project/API-tests
    steps:
      - checkout
      - run:
          name: Install API test dependencies
          command: |
            cd API-tests
            npm install
      - run:
          name: Run API tests
          command: |
            cd mock-user-auth
            npm run test:api
      - store_artifacts:
          path: mock-user-auth/components/mock/routes/report.html
          destination: api-test-report

workflows:
  version: 2
  run-tests:
    jobs:
      - run-api-tests
      - run-ui-tests:
          requires:
            - run-api-tests
